### PR TITLE
Fix markdown floating case

### LINKED ISSUE #1818: Markdown video player floats
https://odysee.com/@dev-test:898c901e7f39b44c5b3f52b1d67a22b185fb3e15?view=about

image

### PR DESCRIPTION
**Pull request by saltrafael**
## Fixes

Issue Number: closes #1818

- `isMarkdownPost` was never being passed down
- also fixed how it identifies if it's floating on the same page but different tab (markdown on channel discussion vs switching to videos etc should start floating)

### CODE REVIEW

File: ui/component/markdownLink/view.jsx [hunk 1]
```diff
@@ -114,7 +112,7 @@ function MarkdownLink(props: Props) {
         uri={lbryUrlFromLink || decodedUri}
         autoEmbed={embed}
         parentCommentId={parentCommentId}
-        isMarkdownPost={isMarkdownPost}
+        isMarkdownPost
```
Comment (infinite-persistence) [inline ui/component/markdownLink/view.jsx:115]: For `MarkdownLink`, is there still different handling needed between Post and non-Post (e.g, comment, livestream, descriptions, etc.)?

_(I vaguely recall it was needed for the Staking thing (show or not show) ... but surrounding code looked different now, so not sure.)_

- If yes, then `isMarkdownPost` shouldn't be removed from the prop list, at least for future use.
- If no, then remove from the 1 remaining instance:

```
            <MarkdownLink
              {...linkProps}
              parentCommentId={parentCommentId}
              isMarkdownPost={isMarkdownPost}  <<<< HERE
              simpleLinks={simpleLinks}
              allowPreview={isStakeEnoughForPreview(stakedLevel) || hasMembership}
              setUserMention={setUserMention}
            />
```

File: flow-typed/content.js [hunk 2]
```diff
@@ -24,7 +24,7 @@ declare type WatchHistory = {
 declare type PlayingUri = {
```
Comment (infinite-persistence) [inline flow-typed/content.js:24]: It's not floating right in the livestreams, but at least it's better than production's where it hijacked the livestream video instead.

image

File: flow-typed/content.js [hunk 3]
```diff
@@ -24,7 +24,7 @@ declare type WatchHistory = {
...
   uri?: ?string,
```
Comment (infinite-persistence) [inline flow-typed/content.js:25]: It broke embed in comments.  It now brings you to the claim rather than playing inline.

File: flow-typed/content.js [hunk 4]
```diff
@@ -24,7 +24,7 @@ declare type WatchHistory = {
...
   primaryUri?: string,
```
Comment (infinite-persistence) [inline flow-typed/content.js:26]: - [ ] Embeds in Post/Comment/Livestream should not autoplay-next (it doesn't in production).

File: ui/component/markdownLink/view.jsx (hunk 1 above)
Comment (saltrafael) [reply ui/component/markdownLink/view.jsx:115]: I think there shouldn't be any different handling ? Because all it does is set `source: 'markdown'` on `PlayingUri` so either way, the source of playing should still be markdown from `<MarkdownLink />`, then comments pass `parentCommentId`, so comment & livestream chat will have `source: 'comment'` and descriptions & posts `source: 'markdown'`

File: flow-typed/content.js (hunk 4 above)
Comment (infinite-persistence) [reply flow-typed/content.js:26]: I still see it happening in d9135b3b, but not reliably.  I think it's due to Lighthouse not working at the moment (https://odysee-workspace.slack.com/archives/C02FH1UGKGR/p1657891988222109).  Let's wait a bit until lighthouse is back -- if still can't reproduce, I'll grab the steps.

- [ ] By the way, if I disable Floating Player in the settings, the Post embeds play in the background (can only hear audio).

File: flow-typed/content.js (hunk 3 above)
Comment (infinite-persistence) [reply flow-typed/content.js:22]: Oh, for the last checkbox, it wasn't playing because the censorship video was in both the Post and Comment.  If already playing in Post, it can't play in Comment unless another embed is played.

Can ignore I guess.

**Review by infinite-persistence — APPROVED** [review]
:+1:
