### PR TITLE
[Header] Changes, fixes and improvements

### LINKED ISSUE #114: Fix layout shift in header
The search bar shifts because space is not pre-allocated for the logo, which gets loaded later.
The CLS score impact is actually pretty low, but it is very annoying, especially when you are trying to type on it immediately after startup.

image

### PR DESCRIPTION
**Pull request by saltrafael**
🟢  live on https://salt.odysee.com

## Fixes

Issue Number: Closes #114

- Refactorings
- Added Tooltips
- Decreased header size by 20%
- Added layout shift prevention for components that need to be loaded in (Wallet balance, profile picture, logo image)
- Added separate smaller values for mobile so it doesn't take much of the screen
- Replaced logo images for SVG icons

### CODE REVIEW

**Comment by tzarebczan** [comment]
This is shifting the video player, at least on mobile. Will do some more testing. 
Screenshot_20211214-094016

File: ui/component/fileRenderFloating/view.jsx [hunk 1]
```diff
@@ -18,6 +18,10 @@ import { useHistory } from 'react-router';
 import { isURIEqual } from 'util/lbryURI';
 import AutoplayCountdown from 'component/autoplayCountdown';
```
Comment (infinite-persistence) [inline ui/component/fileRenderFloating/view.jsx:19]: When switching between floating and normal player, the controls are no longer visible. Not sure how to reproduce, though.

image

File: ui/component/headerNotificationButton/view.jsx [hunk 2]
```diff
@@ -1,51 +1,42 @@
...
+import 'scss/component/_header.scss';
+
+import { ENABLE_UI_NOTIFICATIONS } from 'config';
+import { useHistory } from 'react-router';
 import * as ICONS from 'constants/icons';
-import React from 'react';
+import * as PAGES from 'constants/pages';
+import Button from 'component/button';
 import Icon from 'component/common/icon';
 import NotificationBubble from 'component/notificationBubble';
```
Comment (infinite-persistence) [inline ui/component/headerNotificationButton/view.jsx:10]: From Tom's screenshot, the bubble and stake indicator is touching borders, which is typically not good UI.
Not a show stopper, but should probably rescale accordingly if easy to do.

File: ui/component/header/index.js [hunk 3]
```diff
@@ -1,40 +1,31 @@
-import * as SETTINGS from 'constants/settings';
 import { connect } from 'react-redux';
```
Comment (infinite-persistence) [inline ui/component/header/index.js:1]: It is clipping on my phone.

This screenshot is from emulator, but looks similar on my phone:
image

**Review by infinite-persistence — CHANGES_REQUESTED** [review]
Code review not done yet (27 files, lol!)

But here are some results from quick-testing...

File: ui/component/headerNotificationButton/view.jsx (hunk 2 above)
Comment (saltrafael) [reply ui/component/headerNotificationButton/view.jsx:10]: So I don't know if that was an older version but I did make smaller defaults for mobile so that it wouldn't overflow out, and I noticed on his screenshot he still has the issue of the search being too far left, which was also fixed, will do some testing to find if it's related to the size of the screen

File: ui/component/header/index.js (hunk 3 above)
Comment (tzarebczan) [reply ui/component/header/index.js:1]: It's closer now, but not totally clipping as it did in my screenshot. I thought it was a feature! Lol

File: ui/component/fileRenderFloating/view.jsx (hunk 1 above)
Comment (tzarebczan) [reply ui/component/fileRenderFloating/view.jsx:19]: Was mostly testing on mobile, thx for trying web. Will try some more things to make sure nothing broke.

Comment (tzarebczan) [reply ui/component/fileRenderFloating/view.jsx:19]: Haven't been able to repo the above yet...

File: ui/component/headerCenterMenuButtons/view.jsx [hunk 4]
```diff
@@ -0,0 +1,104 @@
+// @flow
```
Comment (infinite-persistence) [inline ui/component/headerCenterMenuButtons/view.jsx:1]: Rename the folder to `headerMenuButtons` for consistency and easier to search.

File: ui/component/headerCenterMenuButtons/index.js [hunk 5]
```diff
@@ -0,0 +1,31 @@
+import { connect } from 'react-redux';
+import { doSetClientSetting } from 'redux/actions/settings';
+import { ENABLE_NO_SOURCE_CLAIMS, CHANNEL_STAKED_LEVEL_LIVESTREAM } from 'config';
+import { selectActiveChannelStakedLevel } from 'redux/selectors/app';
+import { selectClientSetting } from 'redux/selectors/settings';
+import * as SETTINGS from 'constants/settings';
+import HeaderMenuButtons from './view';
+
+const select = (state, props) => {
+  const { user } = props;
```
Comment (infinite-persistence) [inline ui/component/headerCenterMenuButtons/index.js:10]: I think this broke the "Go Live" button.  Where is `user` coming from -- I don't see it being passed as a prop in the new version, plus I think it usually comes from redux?

**Review by infinite-persistence — CHANGES_REQUESTED** [review]

File: ui/component/fileRenderFloating/view.jsx (hunk 1 above)
Comment (infinite-persistence) [reply ui/component/fileRenderFloating/view.jsx:19]: Can't repro either. Moving on...

File: ui/component/headerCenterMenuButtons/view.jsx [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+
+import { Link } from 'react-router-dom';
+import { Menu, MenuList, MenuButton, MenuItem, MenuLink } from '@reach/menu-button';
+import * as ICONS from 'constants/icons';
+import * as PAGES from 'constants/pages';
+import * as SETTINGS from 'constants/settings';
+import Icon from 'component/common/icon';
+import NotificationHeaderButton from 'component/headerNotificationButton';
+import React from 'react';
+import Tooltip from '@mui/material/Tooltip';
```
Comment (infinite-persistence) [inline ui/component/headerCenterMenuButtons/view.jsx:12]: New tooltip requires styling to match others + text too small

image

image

File: ui/component/headerCenterMenuButtons/view.jsx [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+
```
Comment (infinite-persistence) [inline ui/component/headerCenterMenuButtons/view.jsx:13]: - [ ] Replace all tooltips to use only 1 library -- avoid double library.

Don't want this to be a blocker, but if we are using MUI's tooltip, consider adding a task to replace all existing tooltips to MUI so that we don't bloat up the code.  Also add a task to re-do code splitting for MUI, as this change breaks the existing "suggestion.js" package.

**Review by infinite-persistence — CHANGES_REQUESTED** [review]

File: ui/component/headerNotificationButton/view.jsx (hunk 2 above)
Comment (infinite-persistence) [reply ui/component/headerNotificationButton/view.jsx:10]: Not sure if related or not (but maybe it does since this PR changed the envs): yesterday I updated the envs in Anthony and Salt to minimal customizations, so that it'll mostly grab whatever's in `.env.default` -- no more unexpected overrides.  The next build, if not already, should reflect this.

@tzarebczan, just fyi.  I only updated `Prod-1`, `Prod-2`, `Salt` and `Anthony`.  Left the others alone.  Also kept an original backup in their respective folders.

**Comment by keikari** [comment]
Found some small stuff on mobile version
- LBC amount cut off
- x in search is a bit off
lbc-amount-cut-off
x-not-centered

File: ui/component/headerCenterMenuButtons/view.jsx (hunk 7 above)
Comment (infinite-persistence) [reply ui/component/headerCenterMenuButtons/view.jsx]: We already have `Tooltip` defined, and it's just a simple wrapper.  Maybe change there instead?  The next new person will be confused on which one to use.

This may or may not increase testing time though, since we are unused if the tooltip behavior between Reach and MUI is 1:1 or not.

**Review by infinite-persistence — COMMENTED** [review]
- Few more last minor comments.
- Skipped css part.

File: ui/component/headerMenuButtons/index.js [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+const select = (state) => {
+  const user = selectUser(state);
+
+  const activeChannelStakedLevel = selectActiveChannelStakedLevel(state);
+  const livestreamEnabled = Boolean(
+    ENABLE_NO_SOURCE_CLAIMS &&
+      user &&
+      !user.odysee_live_disabled &&
+      (activeChannelStakedLevel >= CHANNEL_STAKED_LEVEL_LIVESTREAM || user.odysee_live_enabled)
+  );
```
[the remark this answers is not in the document]
Comment (saltrafael) [reply ui/component/headerMenuButtons/index.js:19]: good point thank you!

File: ui/component/headerMenuButtons/index.js [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+    automaticDarkModeEnabled: selectClientSetting(state, SETTINGS.AUTOMATIC_DARK_MODE_ENABLED),
+    currentTheme: selectClientSetting(state, SETTINGS.THEME),
+    livestreamEnabled,
+    user,
+  };
+};
+
+const perform = (dispatch) => ({
+  handleThemeToggle: (automaticDarkModeEnabled, currentTheme) => {
+    if (automaticDarkModeEnabled) dispatch(doSetClientSetting(SETTINGS.AUTOMATIC_DARK_MODE_ENABLED));
```
[the remark this answers is not in the document]
Comment (saltrafael) [reply ui/component/headerMenuButtons/index.js:32]: true!

File: .env.defaults [hunk 10]
```diff
@@ -52,8 +52,8 @@ YRBL_HAPPY_IMG_URL=https://spee.ch/spaceman-happy:a.png?quality=85&height=457&wi
 YRBL_SAD_IMG_URL=https://spee.ch/spaceman-sad:d.png?quality=85&height=457&width=457
```
Comment (infinite-persistence) [inline .env.defaults:52]: Overlap between Settings and Balance

- Split screen 50-50 with another app, 1920x1080 screen (common)
- Full screen + 1080p monitor in portrait (not common)

image

File: ui/component/header/index.js (hunk 3 above)
Comment (infinite-persistence) [reply ui/component/header/index.js:1]: It it still clipping for me on Firefox Android, but also just noticed that Chrome Android does not clip.  Chrome Android also handles the "PRs in this dev instance" bubble better, where the text doesn't overflow the button/

File: ui/component/header/view.jsx [hunk 11]
```diff
@@ -53,220 +27,182 @@ type Props = {
...
+        <>
+          {!hideWallet && (
+            <Tooltip
+              title={
+                balance > 0
+                  ? __('Immediately spendable: %spendable_balance%', { spendable_balance: roundedSpendableBalance })
+                  : __('Your Wallet')
+              }
+            >
+              <div className="test">
```
Comment (infinite-persistence) [inline ui/component/header/view.jsx:142]: Clean up temporary?

File: ui/scss/component/_header.scss [hunk 12]
```diff
@@ -1,3 +1,6 @@
+@import '../init/vars';
```
Comment (infinite-persistence) [inline ui/scss/component/_header.scss:1]: Do we need to apply the same changes in #528 here?

File: ui/scss/component/_header.scss [hunk 13]
```diff
@@ -1,3 +1,6 @@
...
+@import '../init/mixins';
+
 .header {
```
Comment (infinite-persistence) [inline ui/scss/component/_header.scss:4]: [Non blocking]
On a 1280 pixel wide screen, the wunderbar feels a bit squished.  Would be nice if able to maintain the original "fill remaining space, but until a certain max width", but not a big deal.

**Review by infinite-persistence — CHANGES_REQUESTED** [review]
Few more items and it's good to go.
Nobody else seeing the clipping in Firefox Android?

File: ui/component/header/view.jsx (hunk 11 above)
Comment (saltrafael) [reply ui/component/header/view.jsx:142]: whoops

File: ui/component/header/index.js (hunk 3 above)
Comment (saltrafael) [reply ui/component/header/index.js:1]: oh thank you that's probably why. been testing on chrome all the time

**Comment by tzarebczan** [comment]
Screenshot_20211221-101443
Ff Android, no clipping. Looks like this should be good to go shortly, will give it one last whirl.

**Comment by tzarebczan** [comment]
Just saw the comments nevermind, Rafael may have fixed that.

**Comment by tzarebczan** [comment]
Nice job @saltrafael !
