### PR TITLE
fix mobile scrolling issue

### LINKED ISSUE #941: Can't scroll Settings Page in Mobile Layout
Android Firefox ... on in desktop, resize until it goes into Mobile layout.
Then, log in and go to Settings Page.  Can't scroll down ...

### PR DESCRIPTION
**Pull request by MaxKotlan**
## Fixes

Issue Number:
Closes #941 

## What is the current behavior?

cannot scroll after clicking settings on mobile

## What is the new behavior?

can scroll after clicking settings on mobile

## Other information

when the side navigation is destroyed, it enables scrolling

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [x ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

File: ui/component/sideNavigation/view.jsx [hunk 1]
```diff
@@ -377,6 +377,14 @@ function SideNavigation(props: Props) {
     return null;
   }
 
+  React.useEffect(
+    () => () => {
```
Comment (infinite-persistence) [inline ui/component/sideNavigation/view.jsx:381]: Function that returns a function?

Comment (MaxKotlan) [reply ui/component/sideNavigation/view.jsx:381]: It's a really weird syntax, but it is equivalent to componentWillUnmount() 
https://stackoverflow.com/questions/55020041/react-hooks-useeffect-cleanup-for-only-componentwillunmount

Comment (infinite-persistence) [reply ui/component/sideNavigation/view.jsx:381]: Nice.  Btw, would adding a return statement to 
```
  React.useEffect(() => {
    // $FlowFixMe
    document.body.style.overflowY = showOverlay ? 'hidden' : '';
  }, [showOverlay]);
```
to handle the unmounting case be equivalent, or does it have to be an equivalent to `componentWillUnmount`?

Comment (MaxKotlan) [reply ui/component/sideNavigation/view.jsx:381]: I think it can be done that way and I like that way more. I just didn't think to do that. Nice suggestion!

**Comment by tzarebczan** [comment]
Thanks @MaxKotlan, will get some appreciation over!
