### PR TITLE
Textarea/CommentCreate fixes

### LINKED ISSUE #612: Channel mention crash, `@a:A` -> `Invalid claim ID A`
Typing `@a:A` ,`@a:j`,etc... makes channel mention crash page.

crash

### LINKED ISSUE #717: Bug with `doCommentCreate` + `mentioned_channels`
#690 added the ability to pass mentioned channels to `comment.Create`.  This is done parsing the comment message, looking for all channel mentions.

## Enhancement
- [ ] Is it possible to move the burden of parsing the message from the App to Commentron instead?  The app also needs to resolve the channel mentions in order to get the comment ID.

## Bug
- [ ] The part that handles unresolved channels will not work -- if it did, it's just luck. This is because a `dispatch` is not synchronous and may not return when `comment.Create` is called.
    - One might `await` to fix this, but there will be a submission lag (if lots of mentions) waiting for the resolve.  Might need to also do batch resolve to avoid awaiting one by one.
    - That is why I suggested moving this to commentron.  So much work just to send a message.

Example scenario:  Creator copy/pasted a list of channel to tag his moderators.  These channels are not resolved yet.

```
cc:
@ip-chans-3:3
@ip-chans-5:7 
@ip-chans-6:9 
@ip-chans-7:4 
Hey guys, take note.
```

The `mentioned_channels` parameter is messed up. The number of channels is incorrect, not correctly populated, sometimes only partially populated.

image

### PR DESCRIPTION
**Pull request by saltrafael**
## Fixes

Issue Number: closes #612, closes #717

I tried to fix the console errors in #464 as well but seems there is not a fix yet: `https://github.com/mui-org/material-ui/issues/29961`

### CODE REVIEW

File: ui/component/textareaWithSuggestions/view.jsx [hunk 1]
```diff
@@ -102,7 +103,15 @@ export default function TextareaWithSuggestions(props: Props) {
   const suggestionTerm = suggestionValue && suggestionValue.term;
   const isEmote = suggestionValue && suggestionValue.isEmote;
   const isMention = suggestionValue && !suggestionValue.isEmote;
-  const invalidTerm = suggestionTerm && isMention && suggestionTerm.charAt(1) === ':';
+
+  let invalidTerm = suggestionTerm && isMention && suggestionTerm.charAt(1) === ':';
+  if (isMention && suggestionTerm) {
+    try {
+      parseURI(suggestionTerm);
```
Comment (infinite-persistence) [inline ui/component/textareaWithSuggestions/view.jsx:110]: --- just a note ---
I was curious how `parseURI` would perform, since it has been the source of many performance issues and since this will be continuously rendered as the user types.  Seem ok even on debug.  Maybe it was full lbry urls that's slow.

image

**Review by infinite-persistence — CHANGES_REQUESTED** [review]
