### PR TITLE
Transform route-leading menu items to hyperlinks

### LINKED ISSUE #190: Route-leading menu items aren't proper HTML hyperlinks
**Bug**
Links seen in navigation menus cannot be open in a new tab. It is because they are not even semantically hyperlinks.

**To Reproduce**
1. Press any button in the header navigation that opens up a menu list (one of these: publish button, settings, profile picture).
2. Try middleclicking any item in popped up menu.
3. See that it doesn't open in a new tab.
4. Repeat 1.
5. Try dragging list item in the tab drawer.
6. See no response.
7. Press up/down arrows to focus on item.
8. Try pressing <kbd>Ctrl + Enter</kbd>.
9. See that it doesn't create a new tab.
10. Feel inferior, because now you have to duplicate tab to save what you were seeing in the first one 😂

**Expected behavior**
Menu items that lead to pages of multi-page application are expected to act as normal HTML hyperlinks. Item's page should open in a new tab when user presses mousewheel (mouse navigation) on item or when, also retaining focus on it, user presses <kbd>Ctrl + Enter</kbd> (keyboard navigation). Being the normal hyperlink, it should also be imperative to open in a new tab by just dragging it in the tab drawer.

**Screenshots**
image

**System Configuration**

- LBRY Daemon version:
- LBRY App version: Latest web (Do you include it? Can't find it in the web app.)
- LBRY Installation ID:
- Operating system:

**Additional context**
Guess, I can solve it. Just need some free time.

### PR DESCRIPTION
**Pull request by vintprox**
## Fixes

Fixes #190

## What is the current behavior?
Issue about sums it up. As an example, press the cog button in header section, then try doing everything that you expect from the hyperlink on "Settings" or "Help" item. You'll see that nor middleclicking, nor pressing <kbd>Ctrl + Enter</kbd> on any item will ever open in a new tab. This is a bad UX and I can't stand it.

## What is the new behavior?
 - [x] Link can be pressed with mouse wheel, to open the page in a new tab.
 - [x] Link can be pressed with <kbd>Ctrl + Enter</kbd> while selected, to open the page in a new tab.
 - [ ] Link can be dragged around and dropped on the tab drawer, to open the page in a new tab.

Only 2/3 could be done here. I think it's because of the peculiarities brought by Reach components, they can't be dragged: [MenuLink](https://reach.tech/menu-button/#menulink), [MenuItem](https://reach.tech/menu-button/#menuitem).

In most cases, just middleclicking and keyboard navigation are enough, so I think it's a win.

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

File: ui/component/header/view.jsx [hunk 1]
```diff
@@ -324,26 +325,26 @@ const Header = (props: Props) => {
                       )}
                     </MenuButton>
                     <MenuList className="menu__list--header">
-                      <MenuItem className="menu__link" onSelect={() => history.push(`/$/${PAGES.UPLOADS}`)}>
+                      <MenuLink className="menu__link" as={Link} to={`/$/${PAGES.UPLOADS}`}>
```
Comment (vintprox) [inline ui/component/header/view.jsx:328]: Trying to middleclick the `<MenuItem>` with other props in set won't work! I tried it already to introduce very little changes, but no luck.

You press mouse wheel on `<MenuItem>` with `as={Link} to={...}` - it just navigates in the current tab. Undesirable. So, `<MenuLink>` is way more appropriate here. [Reach docs tell so as well...](https://reach.tech/menu-button/#menulink)

File: ui/component/header/view.jsx [hunk 2]
```diff
@@ -5,11 +5,12 @@ import * as SETTINGS from 'constants/settings';
 import * as PAGES from 'constants/pages';
 import React from 'react';
 import { withRouter } from 'react-router';
+import { Link } from 'react-router-dom';
```
Comment (vintprox) [inline ui/component/header/view.jsx:8]: There is no `Link` under `react-router`, so importing from `react-router-dom` is required here. Of course, I could import `withRouter` from there as well, but I don't know your conventions, guys, so I just made a separate line.

`<Link>` component will stand on place of each `<MenuLink>` that has prop `as={Link}` set. It allows us to utilize some declarative syntax for linking rather than pesky `onSelect...`.

File: ui/component/header/view.jsx [hunk 3]
```diff
@@ -324,26 +325,26 @@ const Header = (props: Props) => {
                       )}
                     </MenuButton>
                     <MenuList className="menu__list--header">
-                      <MenuItem className="menu__link" onSelect={() => history.push(`/$/${PAGES.UPLOADS}`)}>
```
Comment (vintprox) [inline ui/component/header/view.jsx:327]: Come on, don't make function for a mere link. I'd assume, React does all that in a batch anyway...

**Comment by tzarebczan** [comment]
Thanks for the issue and PR @vintprox, congrats on the first one! We'll get this reviewed shortly.

**Comment by mayeaux** [comment]
Great PR! That also bugged me a bit but not enough for it to come up on my radar. I appreciate that when it bothered you you sent the fix, nice work, happy to review anything else you send our way as well, cheers!
