### PR TITLE
Batch resolve pin urls

### LINKED ISSUE #1189: change batch claim search by claim id vs resolve batch (comments / related / pinned)
Resolve batching has issues with wrong data coming back, claim search batching seems more accurate. Performance wise they are the same. 

As long as there's less than 50 things to batch, claim search should be fine. If there's more than 50, we'd need to run a 2nd request with page 2 (and 3.. etc). We do this for livestream data, so maybe can re-use that if needed..but I think it's generally less than 50.

In the future, we may revert it back.

### PR DESCRIPTION
**Pull request by infinite-persistence**
Dependency: deploy after PR #1205 
Ticket: closes #1189

<strike>This version includes both the `resolve` and `claim_search` version.  Flip between the 2 using `USE_CLAIM_SEARCH`.

:warning: It's currently using `resolve` (despite buggy) because pin URLs are canonical and I don't know how to derive the claim ID from that -- I don't think there an option to pass urls to `claim_search`?</strike>

### CODE REVIEW

**Comment by tzarebczan** [comment]
yea, no way to pass urls to claim search. How can we properly cutover so it works on both here+android?  Make a new pinnedIds?

**Comment by infinite-persistence** [comment]
## Notes for Drew
- Move from `pinnedUrls` to `pinnedClaimIds`. 
  ```
    pinnedClaimIds: [
    '52582e3e30c2367866a62c7375dd3373f0dbe5fa',
  ],
  ```
- If both are defined, `pinnedUrls` take precedence. Currently, `pinnedUrls` might not appear correctly due to an SDK bug.
- Do switch to `pinnedClaimIds` for all homepages.

## Notes for Tom
If merged now, the existing homepages would be using batched `resolve` instead of `claim_search`, until the homepages are updated to use claim ID.
```
  (1) pinnedUrls     --> uses doResolveUris (resolve)
  (2) pinnedClaimIds --> uses doResolveClaimIds (claim_search)
```

## Notes for tester (Rafael?)
I've tested as much as I can, but another set of eyes on the code would be helpful.  If want to execute the code itself:
- Add `USE_LOCAL_HOMEPAGE_DATA=true` into your local `env`, otherwise it will fetch instead.
- Copy the homepage files from the homepage repo into `/custom` as usual, and make modifications.
- Edit the homepage (e.g. `odysee-en.js`) to use `pinnedClaimIds` instead as noted in the Drew notes above.
- I mostly tested by going into `/$/help`, refresh (to clear claim cache), and let the unrelated `/claim_search|resolve/` settle in devtools.  Clear dev tools, then from the sidebar:
  - Click home to test out `ClaimTileDiscover`.  Also customized to just 1 category to reduce log clutter.
  - Click a category to test out `ClaimListDiscover`.
- Resolved IDs will be excluded from the API call, hence the need to refresh.

File: ui/effects/use-resolve-pins.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+  const hasResolvedPinUris = useFetched(resolvingPinUris);
+
+  React.useEffect(() => {
+    if (resolvedPinUris === undefined && pins && !resolvingPinUris) {
+      if (pins.urls) {
+        doResolveUris(pins.urls, true).finally(() => setResolvedPinUris(pins.urls));
+      } else if (pins.claimIds) {
+        // setResolvingPinUris is only needed for claim_search.
+        // doResolveUris uses selectResolvingUris internally to prevent double call.
+        setResolvingPinUris(true);
```
Comment (saltrafael) [inline ui/effects/use-resolve-pins.js:26]: could use this here as a `ref` maybe? since it will only be checked again in case of a double call? just nitpicking but everything looks good

Comment (infinite-persistence) [reply ui/effects/use-resolve-pins.js:26]: Seems like it needs to remain a state, otherwise the ref change doesn't spark a render and `const hasResolvedPinUris = useFetched(resolvingPinUris);` could be missed.
