### PR TITLE
fix: streaming url changes and add fileGet on embedWrapper

### LINKED ISSUE #2198: Embeds without channel in URL don't play (also anonymous ones)
Embed page loads, but embed can't be played:
https://odysee.com/$/embed/Introductie-Masterclass-Odyssee-V2:f
https://odysee.com/$/embed/supertuxkat-antediluvian-abyssa:1
https://odysee.com/$/embed/Odysee-Song:f

This works:
https://odysee.com/$/embed/@odysee:8/Odysee-Song:f

And this format also works without channel("Share" doesn't give this version):
https://odysee.com/$/embed/Introductie-Masterclass-Odyssee-V2/f162c59c2856239062d62789048d0e876acb0670

### LINKED ISSUE #2206: `/$/latest` "reading 'stream'" crash
- https://sentry.lbry.tech/organizations/odysee/issues/30050
- https://odysee.com/$/latest/@Bicituristas:5

image

### PR DESCRIPTION
**Pull request by saltrafael**
## Fixes

Issue Number: closes #2198 closes #2206

### CODE REVIEW

**Review by infinite-persistence — APPROVED** [review]
:small_blue_diamond:  There is now a double `get` call, with the difference only being in `:` vs `#` in the payload.

Perhaps the root-cause is a missing normalization somewhere in the chain, so the selector returned nothing due to key mismatch?  Just guessing.

Given that ...
 - the bulk of the change is just function-renaming (and looks safe), 
 - the solution is a one-liner that's localized to embeds

... maybe we can live with the double call and not risk another solution that touches shared code with the entire system.  Let's see what @tzarebczan thinks about the double call.

**Comment by tzarebczan** [comment]
I'm ok with that for now, will ship. Ty.

File: ui/redux/actions/file.js [hunk 1]
```diff
@@ -111,86 +111,81 @@ export function doDeleteFileAndMaybeGoBack(
...
+  const state = getState();
+  const alreadyFetching = selectOutpointFetchingForUri(state, uri);
 
-    dispatch({
-      type: ACTIONS.FETCH_FILE_INFO_STARTED,
-      data: {
-        outpoint,
-      },
-    });
+  if (alreadyFetching) return;
```
Comment (infinite-persistence) [inline ui/redux/actions/file.js:122]: :small_blue_diamond: Double-check: what happens to a caller with `onSuccess` when there is a pending fetch?

Not sure if it will impact `doPlayUri --> doPurchaseUri`, but from a function point of view, unclear what's the expectation for all scenarios.

- Caller with callback:
    - Pass:  callback runs +  `FETCH_FILE_INFO_COMPLETED`
    - Fail:  `FETCH_FILE_INFO_FAILED`
    - Fetching:  ?? (dead end, need to listen to other selectors)

Maybe not a concern, but just double-checking.  Haven't tried making an LBC purchase.

**Review by infinite-persistence — COMMENTED** [review]
Minor comments for the new commits

File: ui/redux/actions/file.js (hunk 1 above)
Comment (saltrafael) [reply ui/redux/actions/file.js]: Good point, 5042117bce37d213e10f19976841dfabd060719c should be enough but there might be a better approach without calling again while pending
