### PR TITLE
[Comments] Batch fixes

### LINKED ISSUE #45: Comment section expansion broken with layout change
Start with a medium layout so that it is collapsed:

image

Change the zoom level so that we get to see everything:

image

Note that:
- the "expand" button is missing
- there's a bunch of `resolve`
- pressing Refresh in the Comments card doesn't fix it.

Only a page refresh fixes it.

### LINKED ISSUE #46: Comments: Side effect from batch-resolving
Minor side effect:

In small or medium layout:
1. "Expand" works as normal
2. "More" expands the card and displays the spinner, but the spinner briefly goes away and re-collapses before the comments appearing.

### PR DESCRIPTION
**Pull request by rafael-xmr**
## Fixes

Issue Number: closes #45, closes #46, https://github.com/OdyseeTeam/odysee-frontend/pull/61

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by tzarebczan** [comment]
Sorry, i reverted the other one without seeing this @saltrafael !

File: ui/component/commentsList/index.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ const select = (state, props) => {
 
   if (topLevelComments.length > 0) {
     topLevelComments.map(
-      (comment) => Boolean(makeSelectClaimForUri(comment.channel_url)(state)) && resolvedComments.push(comment)
+      (comment) => makeSelectClaimForUri(comment.channel_url)(state) !== undefined && resolvedComments.push(comment)
```
Comment (infinite-persistence) [inline ui/component/commentsList/index.js:33]: I'm think using `map` for the purpose of iterating is not efficient, since `map` would create the mapped array internally, whether assigned or not.

`filter` makes more sense and readable, as it conveys the intention directly.

`resolvedComments = topLevelComments.filter(.... !== undefined)`

File: ui/component/commentsReplies/view.jsx [hunk 2]
```diff
@@ -1,127 +1,135 @@
...
-      for (let i = 0; i < myChannels.length; i++) {
-        if (myChannels[i].claim_id === channelId) {
-          return true;
-        }
-      }
-    }
-    return false;
-  }
+    const urisToResolve = [];
+    fetchedReplies.map(({ channel_url }) => channel_url !== undefined && urisToResolve.push(channel_url));
```
Comment (infinite-persistence) [inline ui/component/commentsReplies/view.jsx:56]: Use `filter`?

File: ui/component/commentsReplies/view.jsx [hunk 3]
```diff
@@ -1,127 +1,135 @@
...
-        )}
-        {isExpanded && (
-          <div>
-            <div className="comment__replies">
-              <Button className="comment__threadline" aria-label="Hide Replies" onClick={() => setExpanded(false)} />
+  // Wait to only display topLevelComments after resolved or else
+  // other components will try to resolve again, like channelThumbnail
+  React.useEffect(() => {
+    if (!isResolvingReplies) setCommentsToDisplay(fetchedReplies);
+  }, [isResolvingReplies, fetchedReplies]);
```
Comment (infinite-persistence) [inline ui/component/commentsReplies/view.jsx:65]: ## Note; not request for change (unless you feel otherwise)
```
  // Wait to only display topLevelComments after resolved or else
  // other components will try to resolve again, like channelThumbnail
```
The earlier suggestion of using the cache-aware `doResolveUris(..., true)` was for these components as well (any sub-components of `CommentList`).   I'll ask Jessop why we don't make the `true` as the default.

If we went that path, we:
- wouldn't need to filter a `resolvedComments[]`
- wouldn't need an extra `commentsToDisplay[]` state
- wouldn't need the extra effects and variables
All we need is just to `doResolveUris(topLevelComments.map(), true)` and other sub-components to use `true` as well.

**Review by infinite-persistence — COMMENTED** [review]
A couple of performance concerns listed below;  seems to be working otherwise.

File: ui/component/commentsList/view.jsx [hunk 4]
```diff
@@ -206,23 +215,48 @@ function CommentList(props: Props) {
...
+  useEffect(() => {
+    if (!isResolvingComments) setCommentsToDisplay(topLevelComments);
+  }, [isResolvingComments, topLevelComments]);
+
+  // Batch resolve comment channel urls
+  useEffect(() => {
+    if (alreadyResolved) return;
+
+    const urisToResolve = [];
+    topLevelComments.map(({ channel_url }) => channel_url !== undefined && urisToResolve.push(channel_url));
```
[the remark this answers is not in the document]
Comment (saltrafael) [reply ui/component/commentsList/view.jsx:253]: `filter` doesn't work here because it needs only the `channel_url` instead of the whole `Comment` object, so it will still need a new array from its values

File: ui/component/commentsReplies/view.jsx (hunk 3 above)
Comment (saltrafael) [reply ui/component/commentsReplies/view.jsx:65]: The problem was that using `topLevelComments` unresolved would make sub-components like `channelThumbnail` resolve each comment one by one first, and using `resolvedComments` would cause #61 

> Comments inadvertently masked

File: ui/component/commentsList/view.jsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (infinite-persistence) [reply ui/component/commentsList/view.jsx:252]: Oops, missed that.  If that's the case, doing the `push` in a regular loop or  `forEach` would be more appropriate.
- `map` will generate an array based on the return of `push` (`[1, 2, 3, 4 ..]`) that gets discarded in this case -- wasted memory allocation.
- In terms of readability and intention, `map` tells someone that we are generating a same-sized array with transformed object, which is not the case here since we are doing some filtering (skipping undefined urls).

No need to change for now, just something to keep in mind.
