### PR TITLE
Fix embed url param parsing

### LINKED ISSUE #787: oembed - parsing parameters
We're not properly parsing referral and time params in oembed URLs

### PR DESCRIPTION
**Pull request by saltrafael**
## Fixes

Issue Number:  closes #787

Now embeds should work with either referral or timestamp params

### CODE REVIEW

File: web/src/oEmbed.js [hunk 1]
```diff
@@ -45,17 +45,18 @@ async function getClaim(requestUrl) {
...
   const authorName = authorClaim ? authorClaim.value.title || authorClaim.name : 'Anonymous';
   const authorUrlPath = authorClaim && authorClaim.canonical_url.replace('lbry://', '').replace('#', ':');
   const authorUrl = authorClaim ? `${URL}/${authorUrlPath}` : null;
   const thumbnailUrl = value && value.thumbnail && value.thumbnail.url && getThumbnailCdnUrl(value.thumbnail.url);
+
+  const embedUrl = generateEmbedUrlEncoded(claim.name, claim.claim_id, timestamp, referral);
   const videoUrl =
-    generateEmbedUrlEncoded(claim.name, claim.claim_id) +
-    (referrerQuery ? `r=${encodeURIComponent(escapeHtmlProperty(referrerQuery))}` : '');
+    embedUrl + (embedlyReferrer ? `referrer=${encodeURIComponent(escapeHtmlProperty(embedlyReferrer))}` : '');
```
Comment (tzarebczan) [inline web/src/oEmbed.js:59]: Just to be safe, we should probably use the escapeHtmlProperty function on the referral and timestamp parameters also.

File: ui/component/embedTextArea/view.jsx [hunk 2]
```diff
@@ -21,7 +21,7 @@ export default function EmbedTextArea(props: Props) {
   const { claim_id: claimId, name } = claim;
   const input = useRef();
 
-  const streamUrl = generateEmbedUrl(name, claimId, includeStartTime, startTime, referralCode);
+  const streamUrl = generateEmbedUrlEncoded(name, claimId, includeStartTime && startTime, referralCode);
```
Comment (tzarebczan) [inline ui/component/embedTextArea/view.jsx:24]: 99% of the time, the $ should work here and looks nicer. Let's keep the original function?

File: web/src/oEmbed.js (hunk 1 above)
Comment (tzarebczan) [reply web/src/oEmbed.js:59]: Or it can be escaped out in the generateEmbedUrl function too?
