### PR TITLE
[Fix] revert fileRenderFloating vs Mobile change

### LINKED ISSUE #830: Video Player Window Resizing Bugs
**Bug**
When the window is resized between the thresholds for mobile and desktop view, the player restarts and picks up from the last saved point.  This is due to the player being torn down and reinstantiated in the toggle between desktop and mobile.  This can be a bit jarring, especially when the window interacts with desktop tiling behavior that temporarily makes the window smaller than you may ultimately intend it to be.

Additionally, the fullscreen toggle in "mobile" crashes the player.  This only occurs on desktop.  Not on actual mobile devices.

**To Reproduce**

1. Play video on desktop.
2. Shrink the window down to less than 900px.
3. Enlarge the window to greater than 900px

**Expected behavior**
Video plays continuously.

**Actual behavior**
Video restarts when going from large to small and stops when going small to large.

**System Configuration**

Windows 10 w/ Brave v1.35.100
Linux w/ Google Chrome 98.0.4758.80

**Additional context**

I did a git bisect to find that the behavior was introduced [with this commit](https://github.com/OdyseeTeam/odysee-frontend/commit/8c3e37687309e7316cff6fe7b0feb2e3c25c2db4) which refactored some of the mobile player logic.  When on a branch based on this commit, I was able to smooth out the switching by using and saving just the initial value returned from `useIsMobile` in `fileRenderInitiator/view.jsx` and `app/view.jsx`.  However, when applying this to master, this no longer worked.  With the additional changes since then, it may call for a more complete fix from someone with the full context.

Perhaps `useIsMobile` could check for touch events or use the `navigator.platform`? Though that may not be a simple switch if "mobile" is also used interchangeably with "small window layout" in some parts of the app.  This likely requires some discussion with your team.

As for the crash upon clicking "full screen" in the mobile view, this is due to no element with class `vjs-control-bar` being present.  However, this does not appear to be an issue on actual mobile, so depending on the route determined fro the above issue, this one may be fixed for free

image

### PR DESCRIPTION
**Pull request by saltrafael**
## Fixes

Issue Number: closes #830

Best fix for now, but could be appropriate to come up with a better `isMobile` vs `isSmallScreen` as a todo

live on https://salt.odysee.com

### CODE REVIEW

**Comment by tzarebczan** [comment]
- [ ] get a failed to view error when resizing window
- [ ] player still seems to reset, and autoplays (same behavior) when resizing while watching.

File: ui/component/fileRenderFloating/view.jsx [hunk 1]
```diff
@@ -226,69 +145,119 @@ export default function FileRenderFloating(props: Props) {
...
 
     return () => {
-      window.removeEventListener('resize', handleResize);
-      onFullscreenChange(window, 'remove', handleResize);
+      window.removeEventListener('resize', onWindowResize);
+      if (!isFloating) onFullscreenChange(window, 'remove', handleResize);
     };
-  }, [handleResize]);
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [clampToScreenOnResize, handleResize, isFloating]);
```
Comment (infinite-persistence) [inline ui/component/fileRenderFloating/view.jsx:221]: On Safari, the video doesn't resize correctly when changing page zoom:
image

Also, I think we should start entering reasons for why we are disabling lint and flow errors, so it's clear to the next person.  It is rare design to partially exclude something from the dep list (and I think the docs say it is usually wrong), but there's always a reason for everything.  It can be explained like this:
```
// eslint-disable-next-line react-hooks/exhaustive-deps, (blah... on-mount only, etc.)
```

Comment (infinite-persistence) [reply ui/component/fileRenderFloating/view.jsx:221]: Hm .. seems like legacy issue.  Fix only if obvious, else can pass to Rave.  But the lint suggestion is still highly appreciated.  I'll start to do the same.

File: ui/redux/selectors/livestream.js [hunk 2]
```diff
@@ -87,6 +87,18 @@ export const selectActiveLivestreamForChannel = createCachedSelector(
...
+  (state, claimId) => claimId,
+  selectActiveLivestreamForClaimId,
+  (claimId, activeLivestreamForClaim) => {
+    if (!claimId || !activeLivestreamForClaim) {
+      return null;
+    }
+
+    return activeLivestreamForClaim.claimId === claimId || null;
+  }
+)((state, channelId) => String(channelId));
```
Comment (infinite-persistence) [inline ui/redux/selectors/livestream.js:100]: I didn't try this out to be 100% sure, but I think `selectActiveLivestreamForClaimId` would be returning the claim for the given `channelId` anyway, so seems like it's going in circles?

Would using `selectActiveLivestreamForClaimId` and checking if there is a claim be sufficient for clients of `selectIsCurrentClaimLive`?

Comment (infinite-persistence) [reply ui/redux/selectors/livestream.js:100]: If this is somehow needed, then just do some cleanup:
- activeLivestreamForClaim --> activeLivestreamClaim (or claim, or activeLivestreamClaimForId)
- selectIsCurrentClaimLive --> selectIsCurrentClaimLiveForId (keeping the ForXXX to make it clear it's a multi-param selector).

File: ui/component/fileRenderFloating/view.jsx [hunk 3]
```diff
@@ -152,56 +115,12 @@ export default function FileRenderFloating(props: Props) {
 
   const isFree = costInfo && costInfo.cost === 0;
   const canViewFile = isFree || claimWasPurchased;
-  const isPlayable = RENDER_MODES.FLOATING_MODES.includes(renderMode);
-  const isReadyToPlay = isPlayable && (streamingUrl || (fileInfo && fileInfo.completed));
```
[the remark this answers is not in the document]
Comment (tzarebczan) [reply ui/component/fileRenderFloating/view.jsx:156]: File info stuff was for desktop I believe

File: ui/component/swipeableDrawer/view.jsx [hunk 4]
```diff
@@ -31,18 +32,29 @@ export default function SwipeableDrawer(props: Props) {
...
+  }, []);
 
   React.useEffect(() => {
-    if (open && !mobilePlayerDimensions) {
-      const element = document.querySelector(`.file-page__video-container`);
+    // Drawer will follow the cover image on resize, so it's always visible
+    if (open && (!mobilePlayerDimensions || !mobilePlayerDimensions.height)) {
+      handleResize();
+
+      window.addEventListener('resize', handleResize);
```
Comment (infinite-persistence) [inline ui/component/swipeableDrawer/view.jsx:53]: Enhancement:  Might need to debounce these .. I know most of existing ones are doing it either.
Asad's `useOnResize` may or may not be useful (I think it doesn't handle "conditionally register the handle" ... so maybe just debounce the handler?)

File: ui/effects/use-play-next.js [hunk 5]
```diff
@@ -0,0 +1,47 @@
+// @flow
+import React from 'react';
+import { generateListSearchUrlParams, formatLbryUrlForWeb } from 'util/url';
+import { useHistory } from 'react-router';
+
+// Returns web blob from the streaming url
+export default function usePlayNext(
+  isFloating: boolean,
+  collectionId?: string,
```
Comment (infinite-persistence) [inline ui/effects/use-play-next.js:9]: Minor:  I think the signature should be `collectionId: ?string` for this case.  Same goes for the few below ... they aren't optional (must be passed in), but they can be null/undefined.

File: yarn.lock [hunk 6]
```diff
@@ -13921,11 +13921,12 @@ react-dom@^16.8.2:
     prop-types "^15.6.2"
     scheduler "^0.19.0"
 
-react-draggable@^3.3.0:
-  version "3.3.2"
-  resolved "https://registry.yarnpkg.com/react-draggable/-/react-draggable-3.3.2.tgz#966ef1d90f2387af3c2d8bd3516f601ea42ca359"
+react-draggable@^4.4.4:
```
Comment (infinite-persistence) [inline yarn.lock:13924]: :+1: thanks for clearing console errors

File: ui/component/fileRenderFloating/view.jsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (saltrafael) [reply ui/component/fileRenderFloating/view.jsx:156]: I think `completed` comes from file download completed, so could start playing then, in our case we only use streamingUrl
