### PR TITLE
Fix url problems

### LINKED ISSUE #1667: URI replacement issues
bf158ad6

image

Normally, `uri` is sliced off correctly:
  image

However, for the oauth case, there will be a temporary redirect while it re-checks the token, and there is an additional hash. 
- [x] The code seems to be slicing off from the first `:`, causing it to always return to the channel page.

  image

----

- [x] There is also the `replace('#', ':')` issue that only replaces the first match, which we talked about in Slack.

### PR DESCRIPTION
**Pull request by rafael-xmr**
## Fixes

Issue Number: closes #1667

### CODE REVIEW

**Comment by tzarebczan** [comment]
Can you also search for replace('#', ':') to see if it needs to replace all vs 1 instance per KP's comment?

**Comment by tzarebczan** [comment]
Will let @infinite-persistence take a peek before merge, thank you!

File: ui/page/show/view.jsx [hunk 1]
```diff
@@ -159,7 +159,7 @@ export default function ShowPage(props: Props) {
       const windowHref = window.location.href;
       const noUrlParams = search.length === 0;
       if (windowHref.includes('?') && noUrlParams) {
-        history.replaceState(history.state, '', windowHref.substring(0, windowHref.length - 1));
+        history.replaceState(history.state, '', windowHref.substring(0, windowHref.length));
```
Comment (infinite-persistence) [inline ui/page/show/view.jsx:162]: If `substring`-ing the entire string, then can just use the original.
But I think the code is trying to remove a trailing `?`, which the new code wouldn't achieve.  The second parameter is the exclude index, which has become out of bounds.

**Review by infinite-persistence — CHANGES_REQUESTED** [review]
Seems to work in oauth as well. The remaining `replace` that aren't change seems to be channel claims, so I guess we are sure there will only be 1 `#` for those cases.

Only 1 concern regarding the `substring` change below.

**Comment by tzarebczan** [comment]
@infinite-persistence ship if it looks good

File: ui/page/show/view.jsx [hunk 2]
```diff
@@ -138,15 +138,20 @@ export default function ShowPage(props: Props) {
...
-        urlPath.indexOf('?') > 0 ? urlPath.substring(urlPath.indexOf('?')) : search.length > 0 ? search : '';
-      const canonicalUrlPath = '/' + canonicalUrl.replace(/^lbry:\/\//, '').replace(/#/g, ':') + fullParams;
+      const path = urlPath.slice(1).replace(/:/g, '#');
+      // in case query is not part of search, it will be identified as queryString and
+      // passed along on replaceState
+      let queryString;
+      try {
+        ({ queryString } = parseURI(path));
+      } catch (e) {}
+      const canonicalUrlPath = '/' + canonicalUrl.replace(/^lbry:\/\//, '').replace(/#/g, ':');
```
Comment (infinite-persistence) [inline ui/page/show/view.jsx:148]: Saw this yesterday but don't quite understand it. Any example of "query is not part of search" to understand it better?

When feeding into `parseURI`, do we need to replace?  (thought it handles both styles).
Asking just because there are 2 known cases where an actual hash will be there, although probably doesn't matter if you are just looking for `queryString`:

1.  Section hashes.  Used to support in Discover, but probably should continue support since it is standard url stuff. e.g. http://localhost:9090/@Odysee:8#livestream_section
2. Oauth stuff (see initial screenshot).

The new code would have replaced those valid hashes (although again, probably doesn't matter? -- not sure).  The original code only performs the replacement over the `canonical_url` and not the entire path, which seems safer/correct.

Will ship after confirming this.

Comment (infinite-persistence) [reply ui/page/show/view.jsx:148]: Ok, confirmed this is problematic, as the original issue that was impacting oauth came back.  Reverting this specific change fixes it.

Comment (infinite-persistence) [reply ui/page/show/view.jsx:148]: Ok, confirmed this is problematic, as the original issue that was impacting oauth came back.  Reverting this specific change fixes it

Comment (infinite-persistence) [reply ui/page/show/view.jsx:148]: Hm ... I'm confused now ... none of the previous commits solved the original oauth problem. Maybe I got the branch wrong during testing that time.

Reproduce:
- `ip.oidc` branch
- Load http://localhost:9090/@Odysee:8/comicbooks:9
- Refresh.  The url stays correct, but the rendered page is one level above.

Comment (infinite-persistence) [reply ui/page/show/view.jsx:148]: Sorry @saltrafael, forgot to mention that you need to log in first.  Maybe use a temp gmail account to login via oauth in order to not mess up your stuff, since this branch isn't finalized yet.

Comment (saltrafael) [reply ui/page/show/view.jsx]: Let me know if it's better now @infinite-persistence, the problem was that when there's a URI like `http://localhost:9090/@fireship:6/redwood-in-100-seconds#3?t=30` the location "hash" is `3?t=30` (everything after `#`) so parseURI had to strip that as well to get the right uri

Comment (infinite-persistence) [reply ui/page/show/view.jsx]: Yay, I'll give it a try tonight or tomorrow.

File: web/src/html.js [hunk 3]
```diff
@@ -205,7 +205,7 @@ async function buildClaimOgMetadata(uri, claim, overrideOptions = {}, referrerQu
   const title = overrideOptions.title || claimTitle;
   const description = overrideOptions.description || claimDescription;
   const cleanDescription = removeMd(description);
-  const claimPath = `${URL}/${claim.canonical_url.replace('lbry://', '').replace('#', ':')}`;
+  const claimPath = `${URL}/${claim.canonical_url.replace('lbry://', '').replace(/#/, ':')}`;
```
Comment (infinite-persistence) [inline web/src/html.js:208]: This is missing a `g` in the regex, so it is no different from the previous version.

File: ui/component/page/view.jsx [hunk 4]
```diff
@@ -73,11 +73,10 @@ function Page(props: Props) {
   const isLandscapeRotated = useIsMobileLandscape();
   const [sidebarOpen, setSidebarOpen] = usePersistedState('sidebar', false);
 
-  const url = pathname.slice(1).replace(/:/g, '#');
+  const urlPath = `lbry://${(pathname + hash).slice(1).replace(/:/g, '#')}`;
```
Comment (infinite-persistence) [inline ui/component/page/view.jsx:76]: --- Just for documentation ----
- Is the `hash` (i.e. `pathname + hash`) required for `parseURI`?  
  - Or perhaps it's a misunderstanding from one of my past comments?
  - But looking at the change in `bf158ad6`, the original code does put the `hash` into `uri` and passes it to the router.  So, if the `hash` is important LBRY URI, why it is removed in `app/view.jsx`, but then included here?
    - My shallow understanding is that `hash` is only needed for navigation and sub-sectioning, and not part of LBRY URI, so a bit confused with the mixture and comparison with old code.

File: ui/util/lbryURI.js [hunk 5]
```diff
@@ -103,17 +103,18 @@ export function parseURI(url: string, requireProto: boolean = false): LbryUrlObj
   }
 
   // Validate and process modifier
-  const [primaryClaimId, primaryClaimSequence, primaryBidPosition] = parseURIModifier(
+  const [primaryClaimId, primaryClaimSequence, primaryBidPosition, primaryPathHash] = parseURIModifier(
```
Comment (infinite-persistence) [inline ui/util/lbryURI.js:106]: The `primaryPathHash` additional should probably be repeated in the duplicate `web/src` version too, until this was intentionally left out and unneeded for web.

**Review by infinite-persistence — CHANGES_REQUESTED** [review]

File: ui/util/lbryURI.js (hunk 5 above)
Comment (infinite-persistence) [reply ui/util/lbryURI.js:106]: Forgot to mention that I squashed a bit and rebased.

File: ui/component/page/view.jsx (hunk 4 above)
Comment (infinite-persistence) [reply ui/component/page/view.jsx:76]: Ok, confirmed this is an issue.
- oauth branch, logged in via sso
- http://localhost:9090/@Odysee:8
- F5
- It should temporarily have a `#state=12345` while it's redirecting, but should end up back in http://localhost:9090/@Odysee:8.  However, this this change (I think), the hash is put back in.

Comment (saltrafael) [reply ui/component/page/view.jsx:76]: Let me know if this is better now for your branch, the problem was that using uris with `#` instead of `:` would make it part of the `hash` so it would be missing from URI, so it was needed to separate what is used for routing/navigation, and what for the LBRY uri, that's why the parsing and `pathname + hash` (on `app/view.jsx` it just needs the URI, on `show/view.jsx` it replaces the URL with the canonical URI + location data otherwise timestamps, referrals, etc would be lost)

File: ui/util/lbryURI.js [hunk 6]
```diff
@@ -157,7 +160,14 @@ function parseURIModifier(modSeperator: ?string, modValue: ?string) {
...
   if (claimId && (claimId.length > claimIdMaxLength || !claimId.match(/^[0-9a-f]+$/))) {
-    throw new Error(__(`Invalid claim ID %claimId%.`, { claimId }));
+    const hashIndex = claimId.indexOf('#');
+
+    if (hashIndex) {
+      pathHash = claimId.substring(hashIndex, claimId.length);
+      claimId = claimId.substring(0, hashIndex);
+    } else {
+      throw new Error(__(`Invalid claim ID %claimId%.`, { claimId }));
+    }
```
Comment (infinite-persistence) [inline ui/util/lbryURI.js:170]: - [ ] :exclamation: `hashIndex` will always be true because a negative number is 'truthy' in javascript.
- [ ] :arrow_down: `pathHash = claimId.substring(hashIndex, claimId.length);` -- can omit the second parameter if grabbing until the end. Shorter code.
- [ ] :bulb: As a pre-caution to catch future odd urls coming in, validate the new `claimId` length and characters again after stripping off the `pathHash`

**Review by infinite-persistence — APPROVED** [review]
It is working in the oauth branch.  Cool to see both `#state` and `&state` handled.  I wonder if we need to handle others like `&session`, `&response_type`, etc ... I guess we can wait until we encounter them.

Just 1 minor logic error to fix, then good to go.  Thanks!

**Comment by saltrafael** [comment]
This also fixes #1834 by the way

**Comment by infinite-persistence** [comment]
Argh, I submitted #1834 thinking that this was merged.

Looks good.
